// src/App.tsx
import max from 'lodash.max';
import range from 'lodash.range';
import take from 'lodash.take';
import { createMemo, Component, batch } from 'solid-js';
import { createStore, produce } from "solid-js/store";
import Card from './components/Card';
import Config from './components/Config';
import GraphView from './components/GraphView';
import { Algo, initState, isValidOrdering, runBiasedColoring, stringToOrdering } from './model';
import { colors } from './colors';
import { Edge, nbVertices, Position } from './graph';
import * as G from './graph';
import toast, { Toaster } from 'solid-toast';

const App: Component = () => {
  let importDialog: HTMLDialogElement;

  const [state, setState] = createStore(initState);

  const graph = () => state.graphs[state.selectedGraphIdx];

  const partialColoring = createMemo(() => {
    const g = graph();
    const n = g.layout.length;
    const colors: number[] = new Array(n);
    colors.fill(-1);
    const coloring = state.results[state.selectedResultIndex]?.coloring ?? [];
    let m = Math.min(coloring.length, state.currentStep);
    for (let i = 0; i < m; i++) {
      colors[coloring[i].vertex] = coloring[i].color;
    }
    return colors
  })

  const setGraph = (idx: number) => {
    setState(produce(state => {
      state.selectedGraphIdx = idx;
      state.results = [];
      state.selectedAlgorithm = { type: "alpha" };
      state.selectedResultIndex = 0;
      state.currentStep = 0;
    }))
  }

  const setAlgo = (type: string) => {
    setState(produce(state => {
      state.currentStep = 0;
      state.selectedAlgorithm =
        type === "custom"
          ? { type: "custom", ordering: range(0, graph().layout.length) }
          : { type } as Algo
    }))
  }

  const setCustomOrdering = (text: string) => {
    const ordering = stringToOrdering(text);
    if (ordering !== null) {
      setState("selectedAlgorithm", { type: "custom", ordering });
    }
  }

  const compute = () => {
    const algo = state.selectedAlgorithm;
    if (algo.type === "custom" && !isValidOrdering(algo.ordering)) {
      return
    }
    const coloring = runBiasedColoring(state.selectedGraphIdx, graph(), state.selectedAlgorithm);
    if (coloring === null)
      return
    const res = {
      algorithm: state.selectedAlgorithm,
      coloring,
      nbColors: 1 + (max(coloring.map(c => c.color)) ?? -1),
      showNbColors: false
    }
    batch(() => {
      setState("results", results => take([res, ...results], 5));
      setState("selectedResultIndex", 0);
      setState("currentStep", 0);
    });
  }

  const showNbColors = () => {
    if (state.currentStep === nbVertices(graph()) && state.results.length > 0) {
      setState("results", state.selectedResultIndex, "showNbColors", true);
    }
  }

  const previousStep = () => {
    setState("currentStep", step => Math.max(0, step - 1))
  }

  const nextStep = () => {
    batch(() => {
      setState("currentStep", step => Math.min(nbVertices(graph()), step + 1))
      showNbColors();
    })
  }

  const finishColoring = () => {
    batch(() => {
      setState("currentStep", nbVertices(graph()));
      showNbColors();
    })
  }

  const setResultIndex = (idx: number) => {
    setState(produce(state => {
      state.selectedResultIndex = idx;
      if (state.results[idx].showNbColors) {
        state.currentStep = nbVertices(graph());
      } else {
        state.currentStep = 0;
      }
    }))
  }

  const saveGraph = () => {
    const idx = state.selectedGraphIdx;
    if (idx < 5) {
      return;
    }
    const json = JSON.stringify(graph());
    window.localStorage.setItem(`coloring-graph-${idx}`, json);
    toast.success("Le graphe a été sauvegardé sur votre machine");
  }

  const openImportDialog = () => {
    navigator.clipboard
      .readText()
      .then(text => {
        setState("dialogContent", text);
      }).catch(() => {
        setState("dialogContent", "");
      }).finally(() => {
        importDialog.showModal();
      })
  }

  const importGraph = () => {
    const json = state.dialogContent;
    const graph = G.jsonToGraph(json);
    if (graph === null) {
      toast.error("Le texte que vous avez entré ne représente pas un graph valide");
    } else {
      setState("graphs", state.selectedGraphIdx, graph);
    }
    importDialog.close();
  }

  const exportGraph = () => {
    navigator.clipboard.writeText(JSON.stringify(graph()));
    toast.success("Le graphe a été copié dans le presse-papier");
  }

  const configActions = {
    setGraph,
    setAlgo,
    setCustomOrdering,
    compute,
    previousStep,
    nextStep,
    finishColoring,
    setResultIndex,
    saveGraph,
    openImportDialog,
    exportGraph,
  }

  const addVertex = (pos: Position) => {
    setState("graphs", state.selectedGraphIdx, g => G.addVertex(g, pos));
  }

  const moveVertex = (idx: number, pos: Position) => {
    setState("graphs", state.selectedGraphIdx, "layout", idx, pos);
  }

  const addEdge = (u: number, v: number) => {
    setState("graphs", state.selectedGraphIdx, g => G.addEdge(g, u, v));
  }

  const removeVertex = (idx: number) => {
    setState("graphs", state.selectedGraphIdx, g => G.removeVertex(g, idx));
  }

  const removeEdge = (edge: Edge) => {
    setState("graphs", state.selectedGraphIdx, g => G.removeEdge(g, edge));
  }

  const clearGraph = () => {
    setState("graphs", state.selectedGraphIdx, { layout: [], edges: [] });
  }

  const reinitGraph = () => {
    setState("graphs", state.selectedGraphIdx, G.genGraph(state.selectedGraphIdx));
  }


  const graphViewActions = {
    addVertex,
    moveVertex,
    addEdge,
    removeVertex,
    removeEdge,
    clearGraph,
    reinitGraph,
  }

  // view
  return (
    <div class="flex flex-row justify-around items-start">
      <Toaster position="top-right" />
      <div class="p-6 bg-white border border-gray-200 rounded-lg shadow">
        <GraphView
          graph={graph()}
          colors={partialColoring()}
          showLetters={nbVertices(graph()) <= 26}
          {...graphViewActions}
        />
      </div>
      <Card title="Ordre des couleurs">
        <div class="w-32">
          <svg viewBox="0 0 40 200">
            {colors.map((color, i) =>
              <>
                <rect x="0" y={i * 20} width="20" height="20" class={color} />
                <text x="24" y={i * 20 + 16} class="graphtext">{i + 1}</text>
              </>
            )}
          </svg>
        </div>
      </Card>
      <Config
        selectedAlgorithm={state.selectedAlgorithm}
        currentStep={state.currentStep}
        results={state.results}
        selectedResultIndex={state.selectedResultIndex}
        showLetters={nbVertices(graph()) <= 26}
        {...configActions}
      />
      <dialog ref={el => (importDialog = el)} class="dialog">
        <div class="dialog-title">Importer un graphe</div>
        <div class="dialog-body" >
          <textarea
            class="textarea"
            cols="100"
            rows="20"
            onChange={e => setState("dialogContent", e.currentTarget.value)}
          >
            {state.dialogContent}
          </textarea>
        </div>
        <div class="dialog-buttons">
          <button class="btn rounded-lg" onClick={() => importDialog.close()}>Annuler</button>
          <button class="btn rounded-lg" autofocus onClick={importGraph}>OK</button>
        </div>
      </dialog>
    </div>
  )
}

export default App;

// src/App.svelte
<script lang="ts">
  import { arrayOf, range } from '@gbagan/utils';
  import toast, {Toaster} from 'svelte-5-french-toast'
  import { type Mode } from "./types";
  import GraphView from "./components/Graph.svelte";
  import { addEdge, addVertex, emptyGraph, initialGraphs, jsonToGraph,
    moveVertex, nbVertices, removeEdge, removeVertex } from "./lib/graph";
  import Config from "./components/Config.svelte";
  import { tick } from 'svelte';
  import { isValidOrdering, runBiasedColoring, stringToOrdering, type Algo, type Result } from './lib/model';
  import Card from './components/Card.svelte';

  let graphs = $state.raw(initialGraphs);
  let graphIndex = $state(0);
  let graph = $derived(graphs[graphIndex]);
  let mode = $state<Mode>("move");
  let dialogContent = $state("");
  let selectedAlgorithm = $state.raw<Algo>({ type: "alpha" });
  let results: Result[] = $state([]);
  let selectedResultIndex = $state(0);
  let currentStep = $state(0);
 
  let dialogEl!: HTMLDialogElement;
  let importTextArea: HTMLTextAreaElement | undefined = $state();  

  let partialColoring = $derived.by(() => {
    const g = graph;
    const colors = arrayOf(g.layout.length, -1);
    const coloring = results[selectedResultIndex]?.coloring ?? [];
    const m = Math.min(coloring.length, currentStep)
    for (let i = 0; i < m; i++) {
      colors[coloring[i].vertex] = coloring[i].color;
    }
    return colors;
  });

  function setGraph(idx: number) {
    graphIndex = idx;
    results = [];
    selectedAlgorithm = { type: "alpha" };
    selectedResultIndex = 0;
    currentStep = 0;
  }

  function setAlgo(type: string) {
    currentStep = 0;
    selectedAlgorithm =
      type === "custom"
      ? { type: "custom", ordering: range(0, graph.layout.length) }
      : { type: type } as Algo
  }

  function setCustomOrdering(text: string) {
    const ordering = stringToOrdering(text);
    if (ordering !== null) {
      selectedAlgorithm = { type: "custom", ordering };
    }
  }

  function compute() {
    const algo = selectedAlgorithm;
    if (algo.type === "custom" && !isValidOrdering(algo.ordering)) {
      return
    }
    const coloring = runBiasedColoring(graphIndex, graph, selectedAlgorithm);
    if (coloring === null) return;
    const res = {
      algorithm: algo,
      coloring,
      nbColors: 1 + (Math.max(...coloring.map(c => c.color)) ?? -1),
      showNbColors: false
    }
    results = [res, ...results].slice(0, 5);
    selectedResultIndex = 0;
    currentStep = 0;
  }

  function showNbColors() {
    if (currentStep === nbVertices(graph) && results.length > 0) {
      results[selectedResultIndex].showNbColors = true;
    }
  }

  function previousStep() {
    currentStep = Math.max(0, currentStep - 1);
  }

  function nextStep() {
    currentStep = Math.min(nbVertices(graph), currentStep + 1);
    showNbColors();
  }

  function finishColoring() {
    currentStep = nbVertices(graph);
    showNbColors();
  }

  function setResultIndex(idx: number) {
    selectedResultIndex = idx
    if (results[idx].showNbColors) {
      currentStep = nbVertices(graph);
    } else {
      currentStep = 0;
    }
  }
  
  function saveGraph() {
    if (graphIndex < 5) return;
    const json = JSON.stringify(graph);
    window.localStorage.setItem(`coloring-graph-${graphIndex}`, json);
    toast.success("Le graphe a été sauvegardé sur votre machine");
  }

  function importGraph() {
    const g = jsonToGraph(dialogContent);
    if (g === null) {
      toast.error("Le texte que vous avez entré ne représente pas un graphe valide");
    } else {
      graphs = graphs.with(graphIndex, g);
      results = [];
      selectedAlgorithm = { type: "alpha" };
      selectedResultIndex = 0;
      currentStep = 0;
    }
    dialogEl.close();
  }

  function openImportDialog() {
    navigator.clipboard
      .readText()
      .then((text) => dialogContent = text)
      .catch(() => dialogContent = "")
      .finally(async () => {
        dialogEl.showModal();
        await tick();
        importTextArea?.focus();
      })
  }

  function exportGraph() {
    navigator.clipboard.writeText(JSON.stringify(graph));
    toast.success("Le graphe a été copié dans le presse-papier");
  }
</script>

<div class="container">
  <div class="main-container">
    <div class="graph-container">
      <GraphView 
        {graph}
        {mode}
        colors={partialColoring}
        showLetters={nbVertices(graph) <= 26}
        addVertex={pos => graphs = graphs.with(graphIndex, addVertex(graph, pos))}
        moveVertex={(idx, pos) => graphs = graphs.with(graphIndex, moveVertex(graph, idx, pos))}
        addEdge={(u, v) => graphs = graphs.with(graphIndex, addEdge(graph, u, v))}
        removeVertex={(idx) => graphs = graphs.with(graphIndex, removeVertex(graph, idx))}
        removeEdge={(edge) => graphs = graphs.with(graphIndex, removeEdge(graph, edge))}
      />
    </div>
    <div class="btngroup">
      <button
        class={["btn left", { active: mode === "move" }]}
        onclick={() => mode = "move"}
      >
        <span class="check">✓</span> Déplacer
      </button>
      <button
        class={["btn", { active: mode === "addv" }]}
        onclick={() => mode = "addv"}
      >
        <span class="check">✓</span> Ajouter sommet
      </button>
      <button
        class={["btn", { active: mode === "adde" }]}
        onclick={() => mode = "adde"}
      >
        <span class="check">✓</span> Ajouter arête
      </button>
      <button
        class={["btn", { active: mode === "delete" }]}
        onclick={() => mode = "delete"}
      >
        <span class="check">✓</span> Retirer
      </button>
      <button
        class="btn"
        onclick={() => graphs = graphs.with(graphIndex, emptyGraph())}
      >
        Tout effacer
      </button>
      <button
        class="btn right"
        onclick={() => graphs = graphs.with(graphIndex, initialGraphs[graphIndex])}
      >
        Réinitialiser
      </button>
    </div>
  </div>
  <Card title="Ordre des couleurs">
    <div class="colors">
      <svg viewBox="0 0 40 200">
        {#each range(0, 10) as i}
          <rect x="0" y={i * 20} width="20" height="20" style:fill="var(--color-{i+1})" />
          <text x="24" y={i * 20 + 16} class="color-text">{i + 1}</text>
        {/each}
      </svg>
    </div>
  </Card>
  <Config
    {selectedAlgorithm}
    {currentStep}
    {results}
    {selectedResultIndex}
    showLetters={nbVertices(graph) <= 26}
    {setGraph}
    {setAlgo}
    {setCustomOrdering}
    {compute}
    {previousStep}
    {nextStep}
    {finishColoring}
    {setResultIndex}
    {saveGraph}
    {openImportDialog}
    {exportGraph}
  />
</div>
<dialog bind:this={dialogEl}>
  <div class="dialog-title">Importer un graphe</div>
  <div class="dialog-body" >
    <textarea
      class="textarea"
      cols="100"
      rows="20"
      bind:this={importTextArea}
      bind:value={dialogContent}
    ></textarea>
  </div>
  <div class="dialog-buttons">
    <button class="btn rounded-lg" onclick={() => dialogEl.close()}>Annuler</button>
    <button class="btn rounded-lg" onclick={importGraph}>OK</button>
  </div>
</dialog>
<Toaster />

<style>
  .container {
    display: flex;
    justify-content: space-around;
  }

  .main-container {
    display: flex;
    flex-direction: column;
    align-items: center;
    gap: 1rem;
  }

  .graph-container {
    width: 40rem;
    touch-action: none;
    border: 1px solid var(--border);
  }

  dialog {
    border: none;
    background-color: #ffffff;
    border-radius: 0.5rem;
    box-shadow: 0 1px 3px 0 rgb(0 0 0 / 0.1), 0 1px 2px -1px rgb(0 0 0 / 0.1);
  }

  dialog::backdrop {
    background-color: rgb(107 114 128 / 0.7);
  }

  .dialog-title {
    margin: 0;
    padding: 1rem;
    min-height: 2rem;
    border-bottom: 2px solid var(--gray-200);
    font-size: 2.25rem;
    font-weight: 500;
  }

  .dialog-body {
    margin: 0;
    padding: 1.5rem;
    border-bottom: 2px solid var(--gray-200);
  }

  .dialog-buttons {
    padding: 1rem;
    display: flex;
    justify-content: flex-end;
    gap: 1rem;
  }

  .colors {
    width: 8rem;
  }

  .color-text {
    font: bold 12px sans-serif;
    fill: var(--gray-900);
    pointer-events: none;
    touch-action: none;
    user-select: none;
  }
</style>
